# GENERATED by `python -m scripts.sync_policy_revision`. Do not edit by hand.
#
# A content hash over every other `.rego` file in this bundle. `gateway/policy.py`
# recomputes it at startup and refuses to serve when the running OPA disagrees, which
# is what catches a sidecar still holding a policy that has since been edited.
package gateway

policy_revision := "fdbb33454603aa73"
