"""The synthetic fixture tree, as data.

Generated by `build_tree.py` rather than committed as loose files: git does not
reliably preserve symlinks across platforms, and `traps/` needs them (FIX-003).

FIX-001: every byte here is synthetic. No real key, credential, customer record, or
production value exists anywhere in this tree. The decoy paths are *named* like
sensitive locations so canonicalization and policy rules can be tested realistically;
they *contain* only canary strings.
"""

from __future__ import annotations

from typing import Final

#: FIX-002: unique, high-entropy, greppable. Their whole purpose is proving a
#: negative — a canary in an audit record, a metric, an error, or (v1.1) a provider
#: payload is a test failure.
CANARIES: Final[tuple[str, ...]] = (
    "CANARY_PROD_SECRET_7f3a91",
    "CANARY_SSH_KEY_91be4c",
    "CANARY_AWS_KEY_2d10f8",
    "CANARY_ENV_SECRET_c4e802",
    "CANARY_SALARY_DATA_5a7d13",
)

TREE: Final[dict[str, str]] = {
    # -- public: readable by everyone -------------------------------------
    "public/documentation.txt": "Public documentation. Safe to read.\n",
    "public/changelog.md": "# Changelog\n\n- v1: initial synthetic fixture.\n",
    # -- workspace: developer read/write ----------------------------------
    "workspace/notes.txt": "Working notes.\n",
    "workspace/scratch/.keep": "",
    # -- confidential: never readable in v1 policy ------------------------
    "confidential/fake_salaries.csv": (
        f"name,salary,note\nalice,100000,{CANARIES[4]}\nbob,95000,synthetic\n"
    ),
    "confidential/fake_customer_list.csv": "id,name\n1,Synthetic Ltd\n2,Example Inc\n",
    # -- production: never readable ---------------------------------------
    "production/fake_config.env": f"DB_PASSWORD={CANARIES[0]}\nENV=production\n",
    # -- decoys: synthetic stand-ins for real sensitive locations ---------
    "decoys/fake_ssh/id_rsa": (
        f"-----BEGIN FAKE PRIVATE KEY-----\n{CANARIES[1]}\n-----END FAKE PRIVATE KEY-----\n"
    ),
    "decoys/fake_aws/credentials": (
        f"[default]\naws_secret_access_key={CANARIES[2]}\n"
    ),
    "decoys/fake_env/.env": f"API_KEY={CANARIES[3]}\n",
    # -- traps: a real file so the escape target is observable ------------
    "traps/.keep": "",
}

#: Symlinks, relative to the fixture root. Values are link targets.
#: FIX-003: committed as data and rebuilt, so the corpus is reproducible. Where a
#: platform cannot create them, affected scenarios are reported SKIPPED, never passed.
LINKS: Final[dict[str, str]] = {
    "traps/escape_link": "../..",  # escapes the fixture root entirely
    "traps/public_link": "../public",  # legitimate in-root link (false-positive control)
    "traps/loop_a": "loop_b",
    "traps/loop_b": "loop_a",
}

#: Top-level directories and the classification unit 05 derives from them.
#: CANON-013: classification comes from layout under version control, never content.
CLASSIFICATION: Final[dict[str, str]] = {
    "public": "public",
    "workspace": "internal",
    "confidential": "confidential",
    "production": "production",
    "decoys": "secret",
    "traps": "internal",
}
