"""Regenerate approved fingerprints from a LIVE upstream. `_tech/04` §3.

    python -m scripts.fingerprint_tools            # print the TOML blocks
    python -m scripts.fingerprint_tools --check    # exit 1 if the registry has drifted

Prints; never writes. Approving a schema change must be a paste-and-review, because
a registry that updates itself from the upstream detects nothing — the drift check
would compare the upstream against a copy of the upstream and always agree.

`--check` is the developer-facing half: it answers "did I change the fixture and
forget to re-approve?" before a test failure has to. It is NOT the security control;
that is `Registry.verify_schemas`, which runs at startup against the real session and
quarantines rather than reporting.

Launched through `gateway.bridge.upstream`, not a hand-rolled client. The modern era
has no `initialize`, so a session that skips the `server/discover` probe sends no
`_meta` and the fixture's own inbound ladder rejects `tools/list` with -32602 — a
fingerprint generated by a differently-connected client would be a confidently wrong
answer, which is the one thing this script must never produce.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import anyio

from gateway import bridge, registry
from gateway.config import load as load_config

REPO = Path(__file__).resolve().parents[1]


async def advertised_tools(reg: registry.Registry) -> list[dict[str, Any]]:
    """Launch the child exactly as the gateway would and read `tools/list`.

    Launch parameters come from the REGISTRY (REG-002). Reading them from anywhere
    else would mean fingerprinting a different process than the one the gateway runs.
    """
    async with bridge.upstream(reg.server.child_config()) as up:
        result = await up.list_tools()
        # by_alias: the WIRE shape. Without it pydantic emits `input_schema`, which
        # `registry.normalize` refuses — see the guard there for what that cost.
        return [t.model_dump(by_alias=True, exclude_none=True) for t in result.tools]


def toml_block(tool: dict[str, Any], approved: registry.ToolEntry | None) -> str:
    """One `[[server.tool]]` block, ready to paste.

    `risk_tier`, `operation` and `approved_for` carry over from the existing entry:
    they are HUMAN judgements about what the tool does, and the upstream has no say
    in them (REG-008). For a genuinely new tool they are emitted as `REVIEW-ME`,
    which fails `RiskTier` validation at startup — an unreviewed paste must not
    approve a destructive tool at R0.

    `input_schema` also carries over, because it is the APPROVED schema and the whole
    of REG-014 is that it is not the advertised one. For a new tool the advertised
    schema seeds it with `additionalProperties: false` added, since REG-013 requires
    a closed schema and the SDK derives its listing from a handler signature.
    """
    if approved is not None:
        schema_text = approved.input_schema.strip()
    else:
        seed: dict[str, Any] = dict(tool.get("inputSchema") or {"type": "object"})
        seed["additionalProperties"] = False
        schema_text = json.dumps(seed, indent=2, sort_keys=True)
    indented = "\n".join("  " + line for line in schema_text.splitlines())
    return f"""  [[server.tool]]
  name = {json.dumps(tool["name"])}
  risk_tier = {json.dumps(approved.risk_tier if approved else "REVIEW-ME")}
  operation = {json.dumps(approved.operation if approved else "REVIEW-ME")}
  enabled = {"true" if approved is None or approved.enabled else "false"}
  schema_fingerprint = {json.dumps(registry.fingerprint(tool))}
  approved_for = {json.dumps(approved.approved_for if approved else "REVIEW-ME")}
  input_schema = \"\"\"
{indented}
  \"\"\"
"""


def report_drift(reg: registry.Registry, tools: list[dict[str, Any]]) -> int:
    events = reg.verify_schemas(tools)
    for e in events:
        print(f"{e.reason_code}  {e.tool_name}", file=sys.stderr)
        print(f"    approved   {e.approved_fingerprint}", file=sys.stderr)
        print(f"    advertised {e.advertised_fingerprint}", file=sys.stderr)
    if events:
        print(
            f"\n{len(events)} tool(s) differ from the registry. Re-run without "
            "--check, read the diff, and paste it in.",
            file=sys.stderr,
        )
    return 1 if events else 0


async def main() -> int:
    cfg = load_config(REPO / "config" / "gateway.toml")
    reg = registry.Registry.load(REPO / cfg.registry_path)
    tools = await advertised_tools(reg)
    if "--check" in sys.argv:
        return report_drift(reg, tools)
    for tool in tools:
        print(toml_block(tool, reg.tools.get(tool["name"])))
    return 0


if __name__ == "__main__":
    raise SystemExit(anyio.run(main))
