"""Stamp `policies/rego/gateway/revision.rego` with the bundle's content hash.

    python -m scripts.sync_policy_revision            # rewrite the stamp
    python -m scripts.sync_policy_revision --check    # exit 1 if it is stale

Run after editing any `.rego` file. The same shape as `scripts/sync_reason_codes.py`,
and for the same reason: two artifacts have to agree, so exactly one of them is
generated and a test fails when they drift.

What the stamp buys is narrow and worth having. OPA is started against a directory and
`--watch` is deliberately off, so editing a policy and re-running the suite evaluates
the OLD bundle — silently, with every result attributed to the new one. The gateway
hashes the files on disk at startup and refuses to serve unless the running OPA echoes
the same value.
"""

from __future__ import annotations

import sys

from gateway.policy import BUNDLE_DIR, bundle_revision

STAMP = BUNDLE_DIR / "gateway" / "revision.rego"

_TEMPLATE = """\
# GENERATED by `python -m scripts.sync_policy_revision`. Do not edit by hand.
#
# A content hash over every other `.rego` file in this bundle. `gateway/policy.py`
# recomputes it at startup and refuses to serve when the running OPA disagrees, which
# is what catches a sidecar still holding a policy that has since been edited.
package gateway

policy_revision := "{revision}"
"""


def main(argv: list[str]) -> int:
    revision = bundle_revision()
    text = _TEMPLATE.format(revision=revision)
    current = STAMP.read_text("utf-8") if STAMP.exists() else ""

    if "--check" in argv:
        if current.replace("\r\n", "\n") != text:
            print(
                f"{STAMP} is stale: bundle hashes to {revision}.\n"
                "Run `python -m scripts.sync_policy_revision`.",
                file=sys.stderr,
            )
            return 1
        print(f"{STAMP} is current ({revision})")
        return 0

    STAMP.parent.mkdir(parents=True, exist_ok=True)
    STAMP.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {STAMP} ({revision})")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv[1:]))
